import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const tempData = [
  {
    id: "1",
    userType: "Admin",
    firstname: "John Joash Cabanilla",
    middlename: "John Joash Cabanilla",
    lastname: "John Joash Cabanilla",
    email: "john.doe@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.1"
  },
  {
    id: "2",
    userType: "User",
    firstname: "Jane",
    middlename: "Marie",
    lastname: "Smith",
    email: "jane.smith@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.2"
  },
  {
    id: "3",
    userType: "Manager",
    firstname: "Peter",
    middlename: null,
    lastname: "Jones",
    email: "peter.jones@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "172.16.0.3"
  },
  {
    id: "4",
    userType: "User",
    firstname: "Susan",
    middlename: "Anne",
    lastname: "Williams",
    email: "susan.williams@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.4"
  },
  {
    id: "5",
    userType: "Admin",
    firstname: "Robert",
    middlename: "Michael",
    lastname: "Brown",
    email: "robert.brown@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "10.0.0.5"
  },
  {
    id: "6",
    userType: "User",
    firstname: "Linda",
    middlename: null,
    lastname: "Davis",
    email: "linda.davis@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.6"
  },
  {
    id: "7",
    userType: "Manager",
    firstname: "James",
    middlename: "Edward",
    lastname: "Miller",
    email: "james.miller@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.7"
  },
  {
    id: "8",
    userType: "User",
    firstname: "Patricia",
    middlename: "Louise",
    lastname: "Wilson",
    email: "patricia.wilson@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "10.0.0.8"
  },
  {
    id: "9",
    userType: "User",
    firstname: "Charles",
    middlename: null,
    lastname: "Moore",
    email: "charles.moore@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.9"
  },
  {
    id: "10",
    userType: "User",
    firstname: "Elizabeth",
    middlename: "Helen",
    lastname: "Taylor",
    email: "elizabeth.taylor@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "192.168.1.10"
  },
  {
    id: "11",
    userType: "Admin",
    firstname: "Christopher",
    middlename: null,
    lastname: "Anderson",
    email: "christopher.anderson@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.11"
  },
  {
    id: "12",
    userType: "User",
    firstname: "Barbara",
    middlename: "Jean",
    lastname: "Thomas",
    email: "barbara.thomas@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.12"
  },
  {
    id: "13",
    userType: "Manager",
    firstname: "Daniel",
    middlename: "Paul",
    lastname: "Jackson",
    email: "daniel.jackson@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "192.168.1.13"
  },
  {
    id: "14",
    userType: "User",
    firstname: "Jessica",
    middlename: null,
    lastname: "White",
    email: "jessica.white@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.14"
  },
  {
    id: "15",
    userType: "User",
    firstname: "Matthew",
    middlename: "David",
    lastname: "Harris",
    email: "matthew.harris@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.15"
  },
  {
    id: "16",
    userType: "Admin",
    firstname: "Sarah",
    middlename: null,
    lastname: "Martin",
    email: "sarah.martin@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.16"
  },
  {
    id: "17",
    userType: "User",
    firstname: "Kevin",
    middlename: "Andrew",
    lastname: "Thompson",
    email: "kevin.thompson@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.17"
  },
  {
    id: "18",
    userType: "Manager",
    firstname: "Nancy",
    middlename: null,
    lastname: "Garcia",
    email: "nancy.garcia@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "172.16.0.18"
  },
  {
    id: "19",
    userType: "User",
    firstname: "George",
    middlename: "Edward",
    lastname: "Martinez",
    email: "george.martinez@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "192.168.1.19"
  },
  {
    id: "20",
    userType: "User",
    firstname: "Karen",
    middlename: "Lynn",
    lastname: "Robinson",
    email: "karen.robinson@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.20"
  },
  {
    id: "21",
    userType: "User",
    firstname: "Mark",
    middlename: null,
    lastname: "Clark",
    email: "mark.clark@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.21"
  },
  {
    id: "22",
    userType: "Admin",
    firstname: "Lisa",
    middlename: "Michelle",
    lastname: "Rodriguez",
    email: "lisa.rodriguez@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.22"
  },
  {
    id: "23",
    userType: "User",
    firstname: "Steven",
    middlename: "Lee",
    lastname: "Lewis",
    email: "steven.lewis@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "10.0.0.23"
  },
  {
    id: "24",
    userType: "Manager",
    firstname: "Donna",
    middlename: null,
    lastname: "Hall",
    email: "donna.hall@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.24"
  },
  {
    id: "25",
    userType: "User",
    firstname: "Brian",
    middlename: "Thomas",
    lastname: "Allen",
    email: "brian.allen@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.25"
  },
  {
    id: "26",
    userType: "User",
    firstname: "Deborah",
    middlename: "Lynn",
    lastname: "Young",
    email: "deborah.young@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "10.0.0.26"
  },
  {
    id: "27",
    userType: "Admin",
    firstname: "Ronald",
    middlename: null,
    lastname: "King",
    email: "ronald.king@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.27"
  },
  {
    id: "28",
    userType: "User",
    firstname: "Sharon",
    middlename: "Elizabeth",
    lastname: "Wright",
    email: "sharon.wright@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.28"
  },
  {
    id: "29",
    userType: "Manager",
    firstname: "Jeffrey",
    middlename: null,
    lastname: "Scott",
    email: "jeffrey.scott@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "10.0.0.29"
  },
  {
    id: "30",
    userType: "User",
    firstname: "Laura",
    middlename: "Marie",
    lastname: "Green",
    email: "laura.green@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.30"
  },
  {
    id: "31",
    userType: "User",
    firstname: "Gary",
    middlename: null,
    lastname: "Baker",
    email: "gary.baker@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.31"
  },
  {
    id: "32",
    userType: "Admin",
    firstname: "Cynthia",
    middlename: "Ann",
    lastname: "Adams",
    email: "cynthia.adams@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.32"
  },
  {
    id: "33",
    userType: "User",
    firstname: "Dennis",
    middlename: null,
    lastname: "Nelson",
    email: "dennis.nelson@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "172.16.0.33"
  },
  {
    id: "34",
    userType: "Manager",
    firstname: "Kathleen",
    middlename: "Mary",
    lastname: "Carter",
    email: "kathleen.carter@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.34"
  },
  {
    id: "35",
    userType: "User",
    firstname: "Timothy",
    middlename: null,
    lastname: "Phillips",
    email: "timothy.phillips@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "10.0.0.35"
  },
  {
    id: "36",
    userType: "User",
    firstname: "Pamela",
    middlename: "Sue",
    lastname: "Roberts",
    email: "pamela.roberts@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.36"
  },
  {
    id: "37",
    userType: "Admin",
    firstname: "Larry",
    middlename: "Wayne",
    lastname: "Turner",
    email: "larry.turner@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.37"
  },
  {
    id: "38",
    userType: "User",
    firstname: "Helen",
    middlename: null,
    lastname: "Campbell",
    email: "helen.campbell@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.38"
  },
  {
    id: "39",
    userType: "Manager",
    firstname: "Donald",
    middlename: "Lee",
    lastname: "Parker",
    email: "donald.parker@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.39"
  },
  {
    id: "40",
    userType: "User",
    firstname: "Frances",
    middlename: null,
    lastname: "Evans",
    email: "frances.evans@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.40"
  },
  {
    id: "41",
    userType: "User",
    firstname: "Raymond",
    middlename: "Joseph",
    lastname: "Collins",
    email: "raymond.collins@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.41"
  },
  {
    id: "42",
    userType: "Admin",
    firstname: "Joyce",
    middlename: null,
    lastname: "Stewart",
    email: "joyce.stewart@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "172.16.0.42"
  },
  {
    id: "43",
    userType: "User",
    firstname: "Edward",
    middlename: "James",
    lastname: "Sanchez",
    email: "edward.sanchez@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.43"
  },
  {
    id: "44",
    userType: "Manager",
    firstname: "Diane",
    middlename: "Marie",
    lastname: "Morris",
    email: "diane.morris@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "10.0.0.44"
  },
  {
    id: "45",
    userType: "User",
    firstname: "Jose",
    middlename: null,
    lastname: "Rogers",
    email: "jose.rogers@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "172.16.0.45"
  },
  {
    id: "46",
    userType: "User",
    firstname: "Alice",
    middlename: "Elizabeth",
    lastname: "Reed",
    email: "alice.reed@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.46"
  },
  {
    id: "47",
    userType: "Admin",
    firstname: "Walter",
    middlename: null,
    lastname: "Cook",
    email: "walter.cook@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.47"
  },
  {
    id: "48",
    userType: "User",
    firstname: "Shirley",
    middlename: "Ann",
    lastname: "Morgan",
    email: "shirley.morgan@example.com",
    status: "Inactive",
    lastLogIn: "date",
    lastIp: "172.16.0.48"
  },
  {
    id: "49",
    userType: "User",
    firstname: "Arthur",
    middlename: null,
    lastname: "Bell",
    email: "arthur.bell@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "192.168.1.49"
  },
  {
    id: "50",
    userType: "Manager",
    firstname: "Catherine",
    middlename: "Sue",
    lastname: "Bailey",
    email: "catherine.bailey@example.com",
    status: "Active",
    lastLogIn: "date",
    lastIp: "10.0.0.50"
  },
  {
    id: "51",
    userType: "User",
    firstname: "Henry",
    middlename: null,
    lastname: "Cooper",
    email: "henry.cooper@example.com",
    status: "Suspended",
    lastLogIn: "date",
    lastIp: "172.16.0.51"
  },
  {
    id: "52",
    userType: "User",
    firstname: "Jane",
    middlename: null,
    lastname: "Doe",
    email: "jane.doe@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.101"
  },
  {
    id: "53",
    userType: "User",
    firstname: "Peter",
    middlename: "A.",
    lastname: "Jones",
    email: "peter.jones@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "192.168.1.102"
  },
  {
    id: "54",
    userType: "Admin",
    firstname: "Susan",
    middlename: null,
    lastname: "Smith",
    email: "susan.smith@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "10.0.0.5"
  },
  {
    id: "55",
    userType: "User",
    firstname: "Michael",
    middlename: "B.",
    lastname: "Williams",
    email: "michael.williams@example.com",
    status: "Suspended",
    lastLogIn: "2025-07-25",
    lastIp: "172.16.0.55"
  },
  {
    id: "56",
    userType: "User",
    firstname: "Sarah",
    middlename: null,
    lastname: "Brown",
    email: "sarah.brown@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.103"
  },
  {
    id: "57",
    userType: "User",
    firstname: "David",
    middlename: null,
    lastname: "Davis",
    email: "david.davis@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.104"
  },
  {
    id: "58",
    userType: "User",
    firstname: "Emily",
    middlename: "C.",
    lastname: "Miller",
    email: "emily.miller@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "172.16.0.58"
  },
  {
    id: "59",
    userType: "User",
    firstname: "James",
    middlename: null,
    lastname: "Wilson",
    email: "james.wilson@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "10.0.0.6"
  },
  {
    id: "60",
    userType: "User",
    firstname: "Olivia",
    middlename: null,
    lastname: "Moore",
    email: "olivia.moore@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-10",
    lastIp: "192.168.1.105"
  },
  {
    id: "61",
    userType: "User",
    firstname: "Daniel",
    middlename: "D.",
    lastname: "Taylor",
    email: "daniel.taylor@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.106"
  },
  {
    id: "62",
    userType: "User",
    firstname: "Ava",
    middlename: null,
    lastname: "Anderson",
    email: "ava.anderson@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "172.16.0.62"
  },
  {
    id: "63",
    userType: "User",
    firstname: "William",
    middlename: null,
    lastname: "Thomas",
    email: "william.thomas@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "10.0.0.7"
  },
  {
    id: "64",
    userType: "User",
    firstname: "Sophia",
    middlename: "E.",
    lastname: "Jackson",
    email: "sophia.jackson@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-01",
    lastIp: "192.168.1.107"
  },
  {
    id: "65",
    userType: "User",
    firstname: "Joseph",
    middlename: null,
    lastname: "White",
    email: "joseph.white@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.108"
  },
  {
    id: "66",
    userType: "User",
    firstname: "Mia",
    middlename: null,
    lastname: "Harris",
    email: "mia.harris@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "172.16.0.66"
  },
  {
    id: "67",
    userType: "User",
    firstname: "Benjamin",
    middlename: "F.",
    lastname: "Martin",
    email: "benjamin.martin@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "10.0.0.8"
  },
  {
    id: "68",
    userType: "User",
    firstname: "Charlotte",
    middlename: null,
    lastname: "Thompson",
    email: "charlotte.thompson@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "192.168.1.109"
  },
  {
    id: "69",
    userType: "User",
    firstname: "Liam",
    middlename: null,
    lastname: "Garcia",
    email: "liam.garcia@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-05",
    lastIp: "192.168.1.110"
  },
  {
    id: "70",
    userType: "User",
    firstname: "Amelia",
    middlename: "G.",
    lastname: "Martinez",
    email: "amelia.martinez@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "172.16.0.70"
  },
  {
    id: "71",
    userType: "User",
    firstname: "Mason",
    middlename: null,
    lastname: "Robinson",
    email: "mason.robinson@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "10.0.0.9"
  },
  {
    id: "72",
    userType: "User",
    firstname: "Ella",
    middlename: null,
    lastname: "Clark",
    email: "ella.clark@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "192.168.1.111"
  },
  {
    id: "73",
    userType: "User",
    firstname: "Elijah",
    middlename: "H.",
    lastname: "Rodriguez",
    email: "elijah.rodriguez@example.com",
    status: "Suspended",
    lastLogIn: "2025-07-28",
    lastIp: "192.168.1.112"
  },
  {
    id: "74",
    userType: "User",
    firstname: "Chloe",
    middlename: null,
    lastname: "Lewis",
    email: "chloe.lewis@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "172.16.0.74"
  },
  {
    id: "75",
    userType: "User",
    firstname: "Aiden",
    middlename: null,
    lastname: "Lee",
    email: "aiden.lee@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "10.0.0.10"
  },
  {
    id: "76",
    userType: "User",
    firstname: "Zoe",
    middlename: "I.",
    lastname: "Walker",
    email: "zoe.walker@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "192.168.1.113"
  },
  {
    id: "77",
    userType: "User",
    firstname: "Lucas",
    middlename: null,
    lastname: "Hall",
    email: "lucas.hall@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "192.168.1.114"
  },
  {
    id: "78",
    userType: "User",
    firstname: "Grace",
    middlename: null,
    lastname: "Allen",
    email: "grace.allen@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-03",
    lastIp: "172.16.0.78"
  },
  {
    id: "79",
    userType: "User",
    firstname: "Caleb",
    middlename: "J.",
    lastname: "Young",
    email: "caleb.young@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "10.0.0.11"
  },
  {
    id: "80",
    userType: "User",
    firstname: "Lily",
    middlename: null,
    lastname: "Hernandez",
    email: "lily.hernandez@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.115"
  },
  {
    id: "81",
    userType: "User",
    firstname: "Logan",
    middlename: null,
    lastname: "King",
    email: "logan.king@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "192.168.1.116"
  },
  {
    id: "82",
    userType: "User",
    firstname: "Abigail",
    middlename: "K.",
    lastname: "Wright",
    email: "abigail.wright@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-08",
    lastIp: "172.16.0.82"
  },
  {
    id: "83",
    userType: "User",
    firstname: "Carter",
    middlename: null,
    lastname: "Hill",
    email: "carter.hill@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "10.0.0.12"
  },
  {
    id: "84",
    userType: "User",
    firstname: "Isabella",
    middlename: null,
    lastname: "Scott",
    email: "isabella.scott@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.117"
  },
  {
    id: "85",
    userType: "User",
    firstname: "Jackson",
    middlename: "L.",
    lastname: "Adams",
    email: "jackson.adams@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "192.168.1.118"
  },
  {
    id: "86",
    userType: "User",
    firstname: "Scarlett",
    middlename: null,
    lastname: "Baker",
    email: "scarlett.baker@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "172.16.0.86"
  },
  {
    id: "87",
    userType: "User",
    firstname: "Jack",
    middlename: null,
    lastname: "Nelson",
    email: "jack.nelson@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-06",
    lastIp: "10.0.0.13"
  },
  {
    id: "88",
    userType: "User",
    firstname: "Madison",
    middlename: "M.",
    lastname: "Mitchell",
    email: "madison.mitchell@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.119"
  },
  {
    id: "89",
    userType: "User",
    firstname: "Ryan",
    middlename: null,
    lastname: "Perez",
    email: "ryan.perez@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.120"
  },
  {
    id: "90",
    userType: "User",
    firstname: "Layla",
    middlename: null,
    lastname: "Roberts",
    email: "layla.roberts@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "172.16.0.90"
  },
  {
    id: "91",
    userType: "User",
    firstname: "Nolan",
    middlename: "N.",
    lastname: "Turner",
    email: "nolan.turner@example.com",
    status: "Suspended",
    lastLogIn: "2025-07-30",
    lastIp: "10.0.0.14"
  },
  {
    id: "92",
    userType: "User",
    firstname: "Penelope",
    middlename: null,
    lastname: "Phillips",
    email: "penelope.phillips@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.121"
  },
  {
    id: "93",
    userType: "User",
    firstname: "Leo",
    middlename: null,
    lastname: "Campbell",
    email: "leo.campbell@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "192.168.1.122"
  },
  {
    id: "94",
    userType: "User",
    firstname: "Riley",
    middlename: "O.",
    lastname: "Parker",
    email: "riley.parker@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "172.16.0.94"
  },
  {
    id: "95",
    userType: "User",
    firstname: "Victoria",
    middlename: null,
    lastname: "Evans",
    email: "victoria.evans@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "10.0.0.15"
  },
  {
    id: "96",
    userType: "User",
    firstname: "Samuel",
    middlename: null,
    lastname: "Edwards",
    email: "samuel.edwards@example.com",
    status: "Suspended",
    lastLogIn: "2025-08-09",
    lastIp: "192.168.1.123"
  },
  {
    id: "97",
    userType: "User",
    firstname: "Hannah",
    middlename: "P.",
    lastname: "Collins",
    email: "hannah.collins@example.com",
    status: "Active",
    lastLogIn: "2025-08-20",
    lastIp: "192.168.1.124"
  },
  {
    id: "98",
    userType: "User",
    firstname: "Wyatt",
    middlename: null,
    lastname: "Stewart",
    email: "wyatt.stewart@example.com",
    status: "Active",
    lastLogIn: "2025-08-19",
    lastIp: "172.16.0.98"
  },
  {
    id: "99",
    userType: "User",
    firstname: "Aubrey",
    middlename: null,
    lastname: "Morris",
    email: "aubrey.morris@example.com",
    status: "Active",
    lastLogIn: "2025-08-18",
    lastIp: "10.0.0.16"
  },
  {
    id: "100",
    userType: "User",
    firstname: "Luke",
    middlename: "Q.",
    lastname: "Rogers",
    email: "luke.rogers@example.com",
    status: "Active",
    lastLogIn: "2025-08-17",
    lastIp: "192.168.1.125"
  }
];
